package dev.lpsmods.bright.registry;

import dev.lpsmods.bright.Bright;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class BrightItems {
    // Create items
    public static Item COPPER_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_WHITE_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_WHITE_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_LIGHT_GRAY_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_LIGHT_GRAY_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_GRAY_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_GRAY_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_BLACK_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_BLACK_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_BROWN_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_BROWN_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_RED_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_RED_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_ORANGE_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_ORANGE_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_YELLOW_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_YELLOW_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_LIME_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_LIME_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_GREEN_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_GREEN_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_CYAN_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_CYAN_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_LIGHT_BLUE_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_LIGHT_BLUE_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_BLUE_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_BLUE_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_PURPLE_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_PURPLE_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_MAGENTA_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_MAGENTA_CANDLE_STICK, new Item.Settings());
    public static Item COPPER_PINK_CANDLE_STICK = new BlockItem(BrightBlocks.COPPER_PINK_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_WHITE_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_WHITE_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_LIGHT_GRAY_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_LIGHT_GRAY_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_GRAY_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_GRAY_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_BLACK_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_BLACK_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_BROWN_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_BROWN_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_RED_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_RED_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_ORANGE_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_ORANGE_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_YELLOW_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_YELLOW_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_LIME_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_LIME_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_GREEN_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_GREEN_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_CYAN_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_CYAN_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_LIGHT_BLUE_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_LIGHT_BLUE_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_BLUE_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_BLUE_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_PURPLE_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_PURPLE_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_MAGENTA_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_MAGENTA_CANDLE_STICK, new Item.Settings());
    public static Item DIAMOND_PINK_CANDLE_STICK = new BlockItem(BrightBlocks.DIAMOND_PINK_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_WHITE_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_WHITE_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_LIGHT_GRAY_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_LIGHT_GRAY_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_GRAY_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_GRAY_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_BLACK_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_BLACK_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_BROWN_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_BROWN_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_RED_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_RED_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_ORANGE_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_ORANGE_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_YELLOW_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_YELLOW_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_LIME_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_LIME_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_GREEN_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_GREEN_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_CYAN_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_CYAN_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_LIGHT_BLUE_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_LIGHT_BLUE_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_BLUE_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_BLUE_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_PURPLE_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_PURPLE_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_MAGENTA_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_MAGENTA_CANDLE_STICK, new Item.Settings());
    public static Item GOLD_PINK_CANDLE_STICK = new BlockItem(BrightBlocks.GOLD_PINK_CANDLE_STICK, new Item.Settings());
    public static Item IRON_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_CANDLE_STICK, new Item.Settings());
    public static Item IRON_WHITE_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_WHITE_CANDLE_STICK, new Item.Settings());
    public static Item IRON_LIGHT_GRAY_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_LIGHT_GRAY_CANDLE_STICK, new Item.Settings());
    public static Item IRON_GRAY_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_GRAY_CANDLE_STICK, new Item.Settings());
    public static Item IRON_BLACK_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_BLACK_CANDLE_STICK, new Item.Settings());
    public static Item IRON_BROWN_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_BROWN_CANDLE_STICK, new Item.Settings());
    public static Item IRON_RED_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_RED_CANDLE_STICK, new Item.Settings());
    public static Item IRON_ORANGE_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_ORANGE_CANDLE_STICK, new Item.Settings());
    public static Item IRON_YELLOW_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_YELLOW_CANDLE_STICK, new Item.Settings());
    public static Item IRON_LIME_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_LIME_CANDLE_STICK, new Item.Settings());
    public static Item IRON_GREEN_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_GREEN_CANDLE_STICK, new Item.Settings());
    public static Item IRON_CYAN_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_CYAN_CANDLE_STICK, new Item.Settings());
    public static Item IRON_LIGHT_BLUE_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_LIGHT_BLUE_CANDLE_STICK, new Item.Settings());
    public static Item IRON_BLUE_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_BLUE_CANDLE_STICK, new Item.Settings());
    public static Item IRON_PURPLE_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_PURPLE_CANDLE_STICK, new Item.Settings());
    public static Item IRON_MAGENTA_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_MAGENTA_CANDLE_STICK, new Item.Settings());
    public static Item IRON_PINK_CANDLE_STICK = new BlockItem(BrightBlocks.IRON_PINK_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_WHITE_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_WHITE_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_LIGHT_GRAY_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_LIGHT_GRAY_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_GRAY_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_GRAY_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_BLACK_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_BLACK_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_BROWN_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_BROWN_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_RED_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_RED_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_ORANGE_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_ORANGE_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_YELLOW_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_YELLOW_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_LIME_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_LIME_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_GREEN_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_GREEN_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_CYAN_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_CYAN_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_LIGHT_BLUE_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_LIGHT_BLUE_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_BLUE_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_BLUE_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_PURPLE_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_PURPLE_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_MAGENTA_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_MAGENTA_CANDLE_STICK, new Item.Settings());
    public static Item NETHERITE_PINK_CANDLE_STICK = new BlockItem(BrightBlocks.NETHERITE_PINK_CANDLE_STICK, new Item.Settings());

    public static Item WHITE_CEILING_LIGHT = new BlockItem(BrightBlocks.WHITE_CEILING_LIGHT, new Item.Settings());
    public static Item ORANGE_CEILING_LIGHT = new BlockItem(BrightBlocks.ORANGE_CEILING_LIGHT, new Item.Settings());
    public static Item MAGENTA_CEILING_LIGHT = new BlockItem(BrightBlocks.MAGENTA_CEILING_LIGHT, new Item.Settings());
    public static Item LIGHT_BLUE_CEILING_LIGHT = new BlockItem(BrightBlocks.LIGHT_BLUE_CEILING_LIGHT, new Item.Settings());
    public static Item YELLOW_CEILING_LIGHT = new BlockItem(BrightBlocks.YELLOW_CEILING_LIGHT, new Item.Settings());
    public static Item LIME_CEILING_LIGHT = new BlockItem(BrightBlocks.LIME_CEILING_LIGHT, new Item.Settings());
    public static Item PINK_CEILING_LIGHT = new BlockItem(BrightBlocks.PINK_CEILING_LIGHT, new Item.Settings());
    public static Item GRAY_CEILING_LIGHT = new BlockItem(BrightBlocks.GRAY_CEILING_LIGHT, new Item.Settings());
    public static Item LIGHT_GRAY_CEILING_LIGHT = new BlockItem(BrightBlocks.LIGHT_GRAY_CEILING_LIGHT, new Item.Settings());
    public static Item CYAN_CEILING_LIGHT = new BlockItem(BrightBlocks.CYAN_CEILING_LIGHT, new Item.Settings());
    public static Item PURPLE_CEILING_LIGHT = new BlockItem(BrightBlocks.PURPLE_CEILING_LIGHT, new Item.Settings());
    public static Item BLUE_CEILING_LIGHT = new BlockItem(BrightBlocks.BLUE_CEILING_LIGHT, new Item.Settings());
    public static Item BROWN_CEILING_LIGHT = new BlockItem(BrightBlocks.BROWN_CEILING_LIGHT, new Item.Settings());
    public static Item GREEN_CEILING_LIGHT = new BlockItem(BrightBlocks.GREEN_CEILING_LIGHT, new Item.Settings());
    public static Item RED_CEILING_LIGHT = new BlockItem(BrightBlocks.RED_CEILING_LIGHT, new Item.Settings());
    public static Item BLACK_CEILING_LIGHT = new BlockItem(BrightBlocks.BLACK_CEILING_LIGHT, new Item.Settings());

    public static Item WHITE_FLOOR_LIGHT = new BlockItem(BrightBlocks.WHITE_FLOOR_LIGHT, new Item.Settings());
    public static Item ORANGE_FLOOR_LIGHT = new BlockItem(BrightBlocks.ORANGE_FLOOR_LIGHT, new Item.Settings());
    public static Item MAGENTA_FLOOR_LIGHT = new BlockItem(BrightBlocks.MAGENTA_FLOOR_LIGHT, new Item.Settings());
    public static Item LIGHT_BLUE_FLOOR_LIGHT = new BlockItem(BrightBlocks.LIGHT_BLUE_FLOOR_LIGHT, new Item.Settings());
    public static Item YELLOW_FLOOR_LIGHT = new BlockItem(BrightBlocks.YELLOW_FLOOR_LIGHT, new Item.Settings());
    public static Item LIME_FLOOR_LIGHT = new BlockItem(BrightBlocks.LIME_FLOOR_LIGHT, new Item.Settings());
    public static Item PINK_FLOOR_LIGHT = new BlockItem(BrightBlocks.PINK_FLOOR_LIGHT, new Item.Settings());
    public static Item GRAY_FLOOR_LIGHT = new BlockItem(BrightBlocks.GRAY_FLOOR_LIGHT, new Item.Settings());
    public static Item LIGHT_GRAY_FLOOR_LIGHT = new BlockItem(BrightBlocks.LIGHT_GRAY_FLOOR_LIGHT, new Item.Settings());
    public static Item CYAN_FLOOR_LIGHT = new BlockItem(BrightBlocks.CYAN_FLOOR_LIGHT, new Item.Settings());
    public static Item PURPLE_FLOOR_LIGHT = new BlockItem(BrightBlocks.PURPLE_FLOOR_LIGHT, new Item.Settings());
    public static Item BLUE_FLOOR_LIGHT = new BlockItem(BrightBlocks.BLUE_FLOOR_LIGHT, new Item.Settings());
    public static Item BROWN_FLOOR_LIGHT = new BlockItem(BrightBlocks.BROWN_FLOOR_LIGHT, new Item.Settings());
    public static Item GREEN_FLOOR_LIGHT = new BlockItem(BrightBlocks.GREEN_FLOOR_LIGHT, new Item.Settings());
    public static Item RED_FLOOR_LIGHT = new BlockItem(BrightBlocks.RED_FLOOR_LIGHT, new Item.Settings());
    public static Item BLACK_FLOOR_LIGHT = new BlockItem(BrightBlocks.BLACK_FLOOR_LIGHT, new Item.Settings());

    public static Item WHITE_LIGHT_BULB = new BlockItem(BrightBlocks.WHITE_LIGHT_BULB, new Item.Settings());
    public static Item ORANGE_LIGHT_BULB = new BlockItem(BrightBlocks.ORANGE_LIGHT_BULB, new Item.Settings());
    public static Item MAGENTA_LIGHT_BULB = new BlockItem(BrightBlocks.MAGENTA_LIGHT_BULB, new Item.Settings());
    public static Item LIGHT_BLUE_LIGHT_BULB = new BlockItem(BrightBlocks.LIGHT_BLUE_LIGHT_BULB, new Item.Settings());
    public static Item YELLOW_LIGHT_BULB = new BlockItem(BrightBlocks.YELLOW_LIGHT_BULB, new Item.Settings());
    public static Item LIME_LIGHT_BULB = new BlockItem(BrightBlocks.LIME_LIGHT_BULB, new Item.Settings());
    public static Item PINK_LIGHT_BULB = new BlockItem(BrightBlocks.PINK_LIGHT_BULB, new Item.Settings());
    public static Item GRAY_LIGHT_BULB = new BlockItem(BrightBlocks.GRAY_LIGHT_BULB, new Item.Settings());
    public static Item LIGHT_GRAY_LIGHT_BULB = new BlockItem(BrightBlocks.LIGHT_GRAY_LIGHT_BULB, new Item.Settings());
    public static Item CYAN_LIGHT_BULB = new BlockItem(BrightBlocks.CYAN_LIGHT_BULB, new Item.Settings());
    public static Item PURPLE_LIGHT_BULB = new BlockItem(BrightBlocks.PURPLE_LIGHT_BULB, new Item.Settings());
    public static Item BLUE_LIGHT_BULB = new BlockItem(BrightBlocks.BLUE_LIGHT_BULB, new Item.Settings());
    public static Item BROWN_LIGHT_BULB = new BlockItem(BrightBlocks.BROWN_LIGHT_BULB, new Item.Settings());
    public static Item GREEN_LIGHT_BULB = new BlockItem(BrightBlocks.GREEN_LIGHT_BULB, new Item.Settings());
    public static Item RED_LIGHT_BULB = new BlockItem(BrightBlocks.RED_LIGHT_BULB, new Item.Settings());
    public static Item BLACK_LIGHT_BULB = new BlockItem(BrightBlocks.BLACK_LIGHT_BULB, new Item.Settings());

    public static Item WHITE_LIGHT_FIXTURE = new BlockItem(BrightBlocks.WHITE_LIGHT_FIXTURE, new Item.Settings());
    public static Item ORANGE_LIGHT_FIXTURE = new BlockItem(BrightBlocks.ORANGE_LIGHT_FIXTURE, new Item.Settings());
    public static Item MAGENTA_LIGHT_FIXTURE = new BlockItem(BrightBlocks.MAGENTA_LIGHT_FIXTURE, new Item.Settings());
    public static Item LIGHT_BLUE_LIGHT_FIXTURE = new BlockItem(BrightBlocks.LIGHT_BLUE_LIGHT_FIXTURE, new Item.Settings());
    public static Item YELLOW_LIGHT_FIXTURE = new BlockItem(BrightBlocks.YELLOW_LIGHT_FIXTURE, new Item.Settings());
    public static Item LIME_LIGHT_FIXTURE = new BlockItem(BrightBlocks.LIME_LIGHT_FIXTURE, new Item.Settings());
    public static Item PINK_LIGHT_FIXTURE = new BlockItem(BrightBlocks.PINK_LIGHT_FIXTURE, new Item.Settings());
    public static Item GRAY_LIGHT_FIXTURE = new BlockItem(BrightBlocks.GRAY_LIGHT_FIXTURE, new Item.Settings());
    public static Item LIGHT_GRAY_LIGHT_FIXTURE = new BlockItem(BrightBlocks.LIGHT_GRAY_LIGHT_FIXTURE, new Item.Settings());
    public static Item CYAN_LIGHT_FIXTURE = new BlockItem(BrightBlocks.CYAN_LIGHT_FIXTURE, new Item.Settings());
    public static Item PURPLE_LIGHT_FIXTURE = new BlockItem(BrightBlocks.PURPLE_LIGHT_FIXTURE, new Item.Settings());
    public static Item BLUE_LIGHT_FIXTURE = new BlockItem(BrightBlocks.BLUE_LIGHT_FIXTURE, new Item.Settings());
    public static Item BROWN_LIGHT_FIXTURE = new BlockItem(BrightBlocks.BROWN_LIGHT_FIXTURE, new Item.Settings());
    public static Item GREEN_LIGHT_FIXTURE = new BlockItem(BrightBlocks.GREEN_LIGHT_FIXTURE, new Item.Settings());
    public static Item RED_LIGHT_FIXTURE = new BlockItem(BrightBlocks.RED_LIGHT_FIXTURE, new Item.Settings());
    public static Item BLACK_LIGHT_FIXTURE = new BlockItem(BrightBlocks.BLACK_LIGHT_FIXTURE, new Item.Settings());

    public static void register() {
        // Register Items
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_candle_stick"), COPPER_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_white_candle_stick"), COPPER_WHITE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_light_gray_candle_stick"), COPPER_LIGHT_GRAY_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_gray_candle_stick"), COPPER_GRAY_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_black_candle_stick"), COPPER_BLACK_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_brown_candle_stick"), COPPER_BROWN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_red_candle_stick"), COPPER_RED_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_orange_candle_stick"), COPPER_ORANGE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_yellow_candle_stick"), COPPER_YELLOW_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_lime_candle_stick"), COPPER_LIME_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_green_candle_stick"), COPPER_GREEN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_cyan_candle_stick"), COPPER_CYAN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_light_blue_candle_stick"), COPPER_LIGHT_BLUE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_blue_candle_stick"), COPPER_BLUE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_purple_candle_stick"), COPPER_PURPLE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_magenta_candle_stick"), COPPER_MAGENTA_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "copper_pink_candle_stick"), COPPER_PINK_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_candle_stick"), DIAMOND_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_white_candle_stick"), DIAMOND_WHITE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_light_gray_candle_stick"), DIAMOND_LIGHT_GRAY_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_gray_candle_stick"), DIAMOND_GRAY_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_black_candle_stick"), DIAMOND_BLACK_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_brown_candle_stick"), DIAMOND_BROWN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_red_candle_stick"), DIAMOND_RED_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_orange_candle_stick"), DIAMOND_ORANGE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_yellow_candle_stick"), DIAMOND_YELLOW_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_lime_candle_stick"), DIAMOND_LIME_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_green_candle_stick"), DIAMOND_GREEN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_cyan_candle_stick"), DIAMOND_CYAN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_light_blue_candle_stick"), DIAMOND_LIGHT_BLUE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_blue_candle_stick"), DIAMOND_BLUE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_purple_candle_stick"), DIAMOND_PURPLE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_magenta_candle_stick"), DIAMOND_MAGENTA_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "diamond_pink_candle_stick"), DIAMOND_PINK_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_candle_stick"), GOLD_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_white_candle_stick"), GOLD_WHITE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_light_gray_candle_stick"), GOLD_LIGHT_GRAY_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_gray_candle_stick"), GOLD_GRAY_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_black_candle_stick"), GOLD_BLACK_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_brown_candle_stick"), GOLD_BROWN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_red_candle_stick"), GOLD_RED_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_orange_candle_stick"), GOLD_ORANGE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_yellow_candle_stick"), GOLD_YELLOW_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_lime_candle_stick"), GOLD_LIME_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_green_candle_stick"), GOLD_GREEN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_cyan_candle_stick"), GOLD_CYAN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_light_blue_candle_stick"), GOLD_LIGHT_BLUE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_blue_candle_stick"), GOLD_BLUE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_purple_candle_stick"), GOLD_PURPLE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_magenta_candle_stick"), GOLD_MAGENTA_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gold_pink_candle_stick"), GOLD_PINK_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_candle_stick"), IRON_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_white_candle_stick"), IRON_WHITE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_light_gray_candle_stick"), IRON_LIGHT_GRAY_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_gray_candle_stick"), IRON_GRAY_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_black_candle_stick"), IRON_BLACK_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_brown_candle_stick"), IRON_BROWN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_red_candle_stick"), IRON_RED_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_orange_candle_stick"), IRON_ORANGE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_yellow_candle_stick"), IRON_YELLOW_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_lime_candle_stick"), IRON_LIME_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_green_candle_stick"), IRON_GREEN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_cyan_candle_stick"), IRON_CYAN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_light_blue_candle_stick"), IRON_LIGHT_BLUE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_blue_candle_stick"), IRON_BLUE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_purple_candle_stick"), IRON_PURPLE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_magenta_candle_stick"), IRON_MAGENTA_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "iron_pink_candle_stick"), IRON_PINK_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_candle_stick"), NETHERITE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_white_candle_stick"), NETHERITE_WHITE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_light_gray_candle_stick"), NETHERITE_LIGHT_GRAY_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_gray_candle_stick"), NETHERITE_GRAY_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_black_candle_stick"), NETHERITE_BLACK_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_brown_candle_stick"), NETHERITE_BROWN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_red_candle_stick"), NETHERITE_RED_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_orange_candle_stick"), NETHERITE_ORANGE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_yellow_candle_stick"), NETHERITE_YELLOW_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_lime_candle_stick"), NETHERITE_LIME_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_green_candle_stick"), NETHERITE_GREEN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_cyan_candle_stick"), NETHERITE_CYAN_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_light_blue_candle_stick"), NETHERITE_LIGHT_BLUE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_blue_candle_stick"), NETHERITE_BLUE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_purple_candle_stick"), NETHERITE_PURPLE_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_magenta_candle_stick"), NETHERITE_MAGENTA_CANDLE_STICK);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "netherite_pink_candle_stick"), NETHERITE_PINK_CANDLE_STICK);

        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "white_ceiling_light"), WHITE_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "orange_ceiling_light"), ORANGE_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "magenta_ceiling_light"), MAGENTA_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "light_blue_ceiling_light"), LIGHT_BLUE_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "yellow_ceiling_light"), YELLOW_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "lime_ceiling_light"), LIME_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "pink_ceiling_light"), PINK_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gray_ceiling_light"), GRAY_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "light_gray_ceiling_light"), LIGHT_GRAY_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "cyan_ceiling_light"), CYAN_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "purple_ceiling_light"), PURPLE_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "blue_ceiling_light"), BLUE_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "brown_ceiling_light"), BROWN_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "green_ceiling_light"), GREEN_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "red_ceiling_light"), RED_CEILING_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "black_ceiling_light"), BLACK_CEILING_LIGHT);

        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "white_floor_light"), WHITE_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "orange_floor_light"), ORANGE_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "magenta_floor_light"), MAGENTA_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "light_blue_floor_light"), LIGHT_BLUE_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "yellow_floor_light"), YELLOW_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "lime_floor_light"), LIME_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "pink_floor_light"), PINK_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gray_floor_light"), GRAY_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "light_gray_floor_light"), LIGHT_GRAY_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "cyan_floor_light"), CYAN_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "purple_floor_light"), PURPLE_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "blue_floor_light"), BLUE_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "brown_floor_light"), BROWN_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "green_floor_light"), GREEN_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "red_floor_light"), RED_FLOOR_LIGHT);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "black_floor_light"), BLACK_FLOOR_LIGHT);

        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "white_light_bulb"), WHITE_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "orange_light_bulb"), ORANGE_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "magenta_light_bulb"), MAGENTA_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "light_blue_light_bulb"), LIGHT_BLUE_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "yellow_light_bulb"), YELLOW_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "lime_light_bulb"), LIME_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "pink_light_bulb"), PINK_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gray_light_bulb"), GRAY_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "light_gray_light_bulb"), LIGHT_GRAY_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "cyan_light_bulb"), CYAN_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "purple_light_bulb"), PURPLE_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "blue_light_bulb"), BLUE_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "brown_light_bulb"), BROWN_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "green_light_bulb"), GREEN_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "red_light_bulb"), RED_LIGHT_BULB);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "black_light_bulb"), BLACK_LIGHT_BULB);

        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "white_light_fixture"), WHITE_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "orange_light_fixture"), ORANGE_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "magenta_light_fixture"), MAGENTA_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "light_blue_light_fixture"), LIGHT_BLUE_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "yellow_light_fixture"), YELLOW_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "lime_light_fixture"), LIME_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "pink_light_fixture"), PINK_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "gray_light_fixture"), GRAY_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "light_gray_light_fixture"), LIGHT_GRAY_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "cyan_light_fixture"), CYAN_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "purple_light_fixture"), PURPLE_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "blue_light_fixture"), BLUE_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "brown_light_fixture"), BROWN_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "green_light_fixture"), GREEN_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "red_light_fixture"), RED_LIGHT_FIXTURE);
        Registry.register(Registries.ITEM, Identifier.of(Bright.MOD_ID, "black_light_fixture"), BLACK_LIGHT_FIXTURE);
    }
}
